package:
  name: fastchange
  version: 1.0.1

source:
  git_rev:
  git_url: https://github.com/gursky1/fastchange

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - numba

about:
  home: