package:
  name: fastchange
  version: 1.0.2

source:
  path: .

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - numba
# conda convert --platform all C:\Users\15072\anaconda3\envs\build\conda-bld\noarch\fastchange-1.0.2-py_0.tar.bz2 -o outputdir/

about:
  home: https://github.com/gursky1/fastchange
  summary: 'Fast change point detection in Python'
  license: MIT